import { useEffect, useMemo, useState } from 'react'
import { morningApi } from '../api'
import { hhmm, stateLabel } from '../format'
import { MACHINE_STATES } from '../types'
import type { Machine, MachineEvent, MachineState, MachineStateDeclaration, ShiftReport } from '../types'

function machineLabel(machines: Machine[], id: string): string { return machines.find((m) => m.id === id)?.machine_id || id }

export function MachineActivityStage({ report, machines, states, onUpdated, onStateAdded, onNext, onBack }: { report: ShiftReport; machines: Machine[]; states: MachineStateDeclaration[]; onUpdated: (report: ShiftReport) => void; onStateAdded: () => void; onNext: () => void; onBack: () => void }) {
  const [machineId, setMachineId] = useState(machines[0]?.id || ''); const [start, setStart] = useState(''); const [end, setEnd] = useState(''); const [issue, setIssue] = useState(''); const [error, setError] = useState<string | null>(null); const [editingId, setEditingId] = useState<string | null>(null)
  const [stateMachineId, setStateMachineId] = useState(machines[0]?.id || ''); const [stateTime, setStateTime] = useState(''); const [state, setState] = useState<MachineState>('not_tested'); const [stateNote, setStateNote] = useState(''); const [followUp, setFollowUp] = useState(''); const [stateError, setStateError] = useState<string | null>(null)
  useEffect(() => { if (!machineId && machines[0]) setMachineId(machines[0].id); if (!stateMachineId && machines[0]) setStateMachineId(machines[0].id) }, [machines, machineId, stateMachineId])
  const latestStates = useMemo(() => [...states].sort((a,b) => a.declared_at.localeCompare(b.declared_at)), [states])
  const reset = () => { setStart(''); setEnd(''); setIssue(''); setEditingId(null) }
  const save = async () => {
    setError(null); if (!machineId || !start || !end || !issue.trim()) { setError('Machine, start, end and issue are all required.'); return }
    try {
      const updated = editingId ? await morningApi<ShiftReport>(`/api/morning/reports/${report.id}/machine-events/${editingId}`, { method: 'PATCH', body: JSON.stringify({ machine_id: machineId, start_hhmm: start, end_hhmm: end, issue: issue.trim() }) }) : await morningApi<ShiftReport>(`/api/morning/reports/${report.id}/machine-events`, { method: 'POST', body: JSON.stringify({ machine_id: machineId, start_hhmm: start, end_hhmm: end, issue: issue.trim() }) })
      onUpdated(updated); setStateMachineId(machineId); if (end) setStateTime(end); reset()
    } catch (err) { setError(err instanceof Error ? err.message : 'Could not save this event.') }
  }
  const edit = (event: MachineEvent) => { setEditingId(event.id); setMachineId(event.machine_id); setStart(hhmm(event.start_time)); setEnd(hhmm(event.end_time)); setIssue(event.issue) }
  const remove = async (id: string) => { onUpdated(await morningApi<ShiftReport>(`/api/morning/reports/${report.id}/machine-events/${id}`, { method: 'DELETE' })); if (editingId === id) reset() }
  const saveState = async () => {
    setStateError(null); if (!stateMachineId || !stateTime) { setStateError('Machine and declaration time are required.'); return } if (state === 'other' && !stateNote.trim()) { setStateError('Please explain an Other state.'); return }
    try { await morningApi(`/api/morning/reports/${report.id}/machine-states`, { method: 'POST', body: JSON.stringify({ machine_id: stateMachineId, declared_hhmm: stateTime, state, state_note: state === 'other' ? stateNote.trim() : null, follow_up: followUp.trim() || null }) }); setStateNote(''); setFollowUp(''); onStateAdded() } catch (err) { setStateError(err instanceof Error ? err.message : 'Could not save machine state.') }
  }
  return <div className="morning-stage">
    <section><h3 className="morning-section-label">Engineering work</h3><div className="morning-add-form"><label>Machine<select value={machineId} onChange={(e) => setMachineId(e.target.value)}>{machines.map((m) => <option key={m.id} value={m.id}>{m.machine_id}</option>)}</select></label><div className="morning-time-row"><label>Start<input type="time" value={start} onChange={(e) => setStart(e.target.value)} /></label><label>End<input type="time" value={end} onChange={(e) => setEnd(e.target.value)} /></label></div><label>Issue / work performed<textarea value={issue} onChange={(e) => setIssue(e.target.value)} /></label>{error ? <p className="error-text">{error}</p> : null}<button type="button" className="primary" onClick={() => void save()}>{editingId ? 'Save correction' : 'Save work interval'}</button>{editingId ? <button type="button" onClick={reset}>Cancel edit</button> : null}</div><div className="morning-events-list">{report.machine_events.map((event) => <div key={event.id} className="morning-entry-row"><div><strong>{machineLabel(machines, event.machine_id)}</strong><div className="meta">{hhmm(event.start_time)}–{hhmm(event.end_time)} · engineering work</div><div className="meta">{event.issue}</div></div><div className="morning-entry-actions"><button type="button" onClick={() => edit(event)}>Edit</button><button type="button" className="danger" onClick={() => void remove(event.id)}>Remove</button></div></div>)}{!report.machine_events.length ? <p className="empty">No machine work entered yet.</p> : null}</div></section>
    <section className="morning-state-section"><h3 className="morning-section-label">How was the machine left?</h3><p className="meta">Machine state is recorded separately from engineering work time. Work duration is not treated as downtime.</p><div className="morning-add-form"><label>Machine<select value={stateMachineId} onChange={(e) => setStateMachineId(e.target.value)}>{machines.map((m) => <option key={m.id} value={m.id}>{m.machine_id}</option>)}</select></label><label>State at time<select value={state} onChange={(e) => setState(e.target.value as MachineState)}>{MACHINE_STATES.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label><label>Time<input type="time" value={stateTime} onChange={(e) => setStateTime(e.target.value)} /></label>{state === 'other' ? <label>State detail<input value={stateNote} onChange={(e) => setStateNote(e.target.value)} placeholder="Describe the state" /></label> : null}<label>Follow-up / unresolved (optional)<textarea value={followUp} onChange={(e) => setFollowUp(e.target.value)} /></label>{stateError ? <p className="error-text">{stateError}</p> : null}<button type="button" onClick={() => void saveState()}>Record machine state</button></div><div className="morning-events-list">{latestStates.map((item) => <div key={item.id} className="morning-entry-row"><div><strong>{machineLabel(machines, item.machine_id)} · {stateLabel(item.state)}</strong><div className="meta">{hhmm(item.declared_at)} · {item.provenance === 'carried' ? 'carried from prior declaration' : 'declared this shift'}</div>{item.state_note ? <div className="meta">{item.state_note}</div> : null}{item.follow_up ? <div className="meta">Follow-up: {item.follow_up}</div> : null}</div></div>)}{!latestStates.length ? <p className="empty">No machine states declared yet.</p> : null}</div></section>
    <div className="morning-stage-nav"><button type="button" onClick={onBack}>Back</button><button type="button" className="primary" onClick={onNext}>Next: Other activities</button></div>
  </div>
}
