import { useState } from 'react'
import { morningApi } from '../api'
import { hhmm, stateLabel } from '../format'
import type { Machine, MachineStateDeclaration, MorningPrincipal, Person, ShiftReport } from '../types'
function machineLabel(machines: Machine[], id: string): string { return machines.find((m) => m.id === id)?.machine_id || id }
function personName(people: Person[], id: string): string { return people.find((p) => p.id === id)?.name || id }

export function ReviewStage({ report, machines, people, states, principal, onBack, onSubmitted, submitted = false }: { report: ShiftReport; machines: Machine[]; people: Person[]; states: MachineStateDeclaration[]; principal?: MorningPrincipal; onBack?: () => void; onSubmitted?: (report: ShiftReport) => void; submitted?: boolean }) {
  const [pending, setPending] = useState(false); const [error, setError] = useState<string | null>(null); const [whatsapp, setWhatsapp] = useState<string | null>(null); const [copied, setCopied] = useState(false)
  const presentCount = report.attendance.filter((e) => e.present).length; const absentCount = report.attendance.filter((e) => !e.present).length; const openStopFix = report.stop_fix.filter((sf) => sf.status === 'open').length; const greenCards = report.cards.filter((c) => c.card_type === 'green').length; const redCards = report.cards.filter((c) => c.card_type === 'red').length
  const loadWhatsapp = async () => setWhatsapp((await morningApi<{ text: string }>(`/api/morning/reports/${report.id}/whatsapp`)).text)
  const submit = async () => { setPending(true); setError(null); try { const result = await morningApi<ShiftReport>(`/api/morning/reports/${report.id}/submit`, { method: 'POST', body: '{}' }); onSubmitted?.(result); await loadWhatsapp() } catch (err) { setError(err instanceof Error ? err.message : 'Could not submit this report.') } finally { setPending(false) } }
  const copy = async () => { if (!whatsapp) return; try { await navigator.clipboard.writeText(whatsapp); setCopied(true); setTimeout(() => setCopied(false), 2000) } catch { setError('Could not copy automatically — select and copy the text below.') } }
  if (submitted || whatsapp) return <div className="morning-stage"><p className="morning-submitted-banner">Shift report submitted.</p><div className="morning-add-form">{whatsapp ? <><textarea className="morning-whatsapp-text" readOnly value={whatsapp} rows={16} /><button type="button" className="primary" onClick={() => void copy()}>{copied ? 'Copied!' : 'Copy report'}</button></> : <button type="button" onClick={() => void loadWhatsapp()}>Show WhatsApp text</button>}</div></div>
  return <div className="morning-stage"><div className="morning-review-summary"><div className="morning-review-row"><span>Shift</span><strong>{report.shift_kind === 'day' ? 'Day' : 'Night'} — {report.shift_date}</strong></div>{principal ? <div className="morning-review-row"><span>Supervisor</span><strong>{principal.display_name}</strong></div> : null}<div className="morning-review-row"><span>Attendance</span><strong>{presentCount} present, {absentCount} absent</strong></div><div className="morning-review-row"><span>Safety</span><strong>{openStopFix} Stop &amp; Fix open, {greenCards} green / {redCards} red cards</strong></div><div className="morning-review-row"><span>Machine work</span><strong>{report.machine_events.length} interval(s)</strong></div><div className="morning-review-row"><span>Machine states</span><strong>{states.length} declaration(s)</strong></div><div className="morning-review-row"><span>Other activities</span><strong>{report.other_activities.length}</strong></div></div>
    {states.length ? <details className="morning-review-detail"><summary>Machine states</summary>{states.map((item) => <div key={item.id} className="meta">{machineLabel(machines, item.machine_id)} · {hhmm(item.declared_at)} · {stateLabel(item.state)}{item.provenance === 'carried' ? ' (carried)' : ''}</div>)}</details> : null}
    {report.machine_events.length ? <details className="morning-review-detail"><summary>Machine work</summary>{report.machine_events.map((event) => <div key={event.id} className="meta">{machineLabel(machines, event.machine_id)}: {event.issue}</div>)}</details> : null}
    {report.attendance.filter((e) => !e.present).length ? <details className="morning-review-detail"><summary>Absent</summary>{report.attendance.filter((e) => !e.present).map((e) => <div key={e.person_id} className="meta">{personName(people, e.person_id)}</div>)}</details> : null}
    {error ? <p className="error-text">{error}</p> : null}<div className="morning-stage-nav">{onBack ? <button type="button" onClick={onBack}>Back</button> : null}<button type="button" className="primary" disabled={pending} onClick={() => void submit()}>{pending ? 'Submitting…' : 'Submit shift report'}</button></div>
  </div>
}
