import { useState } from 'react'
import { morningApi } from '../api'
import { STOP_FIX_AREAS } from '../types'
import type { ShiftReport } from '../types'

export function SafetyStage({ report, onUpdated, onNext, onBack }: { report: ShiftReport; onUpdated: (report: ShiftReport) => void; onNext: () => void; onBack: () => void }) {
  const [sfNumber, setSfNumber] = useState(''); const [sfArea, setSfArea] = useState<string>(STOP_FIX_AREAS[0]); const [sfLocation, setSfLocation] = useState(''); const [sfReason, setSfReason] = useState(''); const [sfInstruction, setSfInstruction] = useState('')
  const [cardType, setCardType] = useState<'red' | 'green'>('green'); const [cardReason, setCardReason] = useState('')
  const addStopFix = async () => {
    if (!sfNumber.trim() || !sfLocation.trim() || !sfReason.trim() || !sfInstruction.trim()) return
    const updated = await morningApi<ShiftReport>(`/api/morning/reports/${report.id}/stop-fix`, { method: 'POST', body: JSON.stringify({ number: sfNumber.trim(), area_of_concern: sfArea, location: sfLocation.trim(), reason: sfReason.trim(), instruction: sfInstruction.trim() }) })
    onUpdated(updated); setSfNumber(''); setSfLocation(''); setSfReason(''); setSfInstruction('')
  }
  const toggleRectified = async (id: string, currentlyOpen: boolean) => onUpdated(await morningApi<ShiftReport>(`/api/morning/reports/${report.id}/stop-fix/${id}`, { method: 'PATCH', body: JSON.stringify({ status: currentlyOpen ? 'rectified' : 'open' }) }))
  const deleteStopFix = async (id: string) => onUpdated(await morningApi<ShiftReport>(`/api/morning/reports/${report.id}/stop-fix/${id}`, { method: 'DELETE' }))
  const addCard = async () => { if (!cardReason.trim()) return; onUpdated(await morningApi<ShiftReport>(`/api/morning/reports/${report.id}/cards`, { method: 'POST', body: JSON.stringify({ card_type: cardType, reason: cardReason.trim() }) })); setCardReason('') }
  const deleteCard = async (id: string) => onUpdated(await morningApi<ShiftReport>(`/api/morning/reports/${report.id}/cards/${id}`, { method: 'DELETE' }))
  return <div className="morning-stage">
    <section className="morning-safety-section"><h2>Stop &amp; Fix</h2>{report.stop_fix.map((item) => <div key={item.id} className="morning-entry-row"><div><strong>{item.number}</strong><div className="meta">{item.area_of_concern} · {item.location}</div><div className="meta">{item.reason}</div></div><div className="morning-entry-actions"><button type="button" onClick={() => void toggleRectified(item.id, item.status === 'open')}>{item.status === 'open' ? 'Mark rectified' : 'Reopen'}</button><button type="button" className="danger" onClick={() => void deleteStopFix(item.id)}>Remove</button></div></div>)}<div className="morning-add-form"><input placeholder="Stop & Fix number" value={sfNumber} onChange={(e) => setSfNumber(e.target.value)} /><select value={sfArea} onChange={(e) => setSfArea(e.target.value)}>{STOP_FIX_AREAS.map((area) => <option key={area} value={area}>{area}</option>)}</select><input placeholder="Machinery / area / location" value={sfLocation} onChange={(e) => setSfLocation(e.target.value)} /><textarea placeholder="Reason / hazard" value={sfReason} onChange={(e) => setSfReason(e.target.value)} /><textarea placeholder="Instruction / action required" value={sfInstruction} onChange={(e) => setSfInstruction(e.target.value)} /><button type="button" onClick={() => void addStopFix()}>Add Stop &amp; Fix</button></div></section>
    <section className="morning-safety-section"><h2>Red / Green cards</h2>{report.cards.map((card) => <div key={card.id} className="morning-entry-row"><div><span className={`morning-card-dot ${card.card_type}`} aria-hidden /><strong>{card.card_type === 'red' ? 'Red' : 'Green'}</strong><span className="meta"> — {card.reason}</span></div><button type="button" className="danger" onClick={() => void deleteCard(card.id)}>Remove</button></div>)}<div className="morning-add-form"><div className="morning-card-toggle"><button type="button" className={cardType === 'green' ? 'morning-card-green active' : 'morning-card-green'} onClick={() => setCardType('green')}>Green</button><button type="button" className={cardType === 'red' ? 'morning-card-red active' : 'morning-card-red'} onClick={() => setCardType('red')}>Red</button></div><input placeholder="Reason" value={cardReason} onChange={(e) => setCardReason(e.target.value)} /><button type="button" onClick={() => void addCard()}>Add card</button></div></section>
    <div className="morning-stage-nav"><button type="button" onClick={onBack}>Back</button><button type="button" className="primary" onClick={onNext}>Next: Machine activity</button></div>
  </div>
}
